### ISSUE TITLE
Add more description in readme for easy and fast start work

### ISSUE THREAD

**Issue by ghost** [MadProbe/tsk#1]
Add `npm i` to instruction and maybe some yet. And I would like to run the translator in the local version. Also i am hope that will be added describe language about what is it. (excuse me for my bad English)

**Comment by MadProbe** [comment]
What should i include in language description?

**Comment by ghost** [comment]
I think that should be description philosophy and goals of language if say about general idea. Here i mean not syntax or some other but dreams. Anyway i hope also see a tour of TSK over time. :star2:

**Comment by MadProbe** [comment]
OK, i'll add this later
